# Input/Output
input_dir: "/net/beliveau/vol2/instrument/E9.5_225/Zoom_225"  
input_xml: "/net/beliveau/vol2/instrument/E9.5_225/Zoom_225/Zoom_225_processed_writable.xml"
# BigStitcher-Spark settings
bigstitcher_script_dir: "/net/beliveau/vol1/project/BigStitcher-Spark"

# Stitching parameters
stitching_channel: 2  # Channel to use for stitching
min_correlation: 0.7  # Minimum correlation threshold for stitching


# Fusion parameters
channels: [0,1,2]  # List of channels to process
block_size: "512,512,512"  # Block size for N5 output
intensity:
  min: 0
  max: 65535
data_type: "UINT16"  # Options: UINT8, UINT16

# Spark cluster configuration
runtime: "8:00"  # Runtime in HH:MM format
n_nodes: 12      # Number of worker nodes
spark_job_timeout: 43200 # Timeout in seconds for waiting on spark job logs (e.g., 12 hours)
cluster:
  executors_per_node: 2
  cores_per_executor: 5
  overhead_cores_per_worker: 1
  tasks_per_executor_core: 2
  cores_driver: 1
  gb_per_slot: 15
  ram_per_core: "12G"  # Amount of RAM per core for worker processes
  project: "beliveaulab"  # Add additional projects as needed
  queue: "beliveau-long.q"    # Optional: specify queue name


# Dask configuration
dask:
  log_dir: "/net/beliveau/vol1/project/VB_Segmentation/subprojects/OTLS-Analyzer/logs"
  runtime: "14000000"

  gpu_project: "shendure_beliveau"
  gpu_queue: "shendure-long.q"
  num_gpu_workers: 24
  gpu_cores: 1
  gpu_memory: "120G"
  gpu_resource_spec: "gpgpu=1,cuda=1,mfree=120G"
  gpu_processes: 2
  
  cpu_project: "beliveaulab"
  cpu_queue: "beliveau-long.q"
  num_cpu_workers: 24
  cpu_cores: 2
  cpu_memory: "60G"
  cpu_resource_spec: "mfree=60G"
  cpu_processes: 2

# Segmentation parameters
segmentation:
  script: "segmentation/segment_fused_image_alternative.py"
  output_suffix: "_segmented_normalized.zarr"
  block_size: "512,512,512" # Example
  eval_kwargs: "{'anisotropy': 1, 'do_3D': True, 'cellprob_threshold': -1, 'batch_size': 128, 'flow_threshold': 0.4, 'normalize': False, 'min_size': 4000}" # Example
  cellpose_model_path: "/net/beliveau/vol1/project/VB_Segmentation/subprojects/Tissue_Segmentation_Revisited/models/cellpose_otls/otls_r5"
  n5_channel_path: "ch2/s0" # Define the path within N5 for segmentation input

feature_extraction:
  channels: [0,1,2]
  script: "feature_extraction/distributed_feature_extraction.py"
  n5_path_pattern: "ch{}/s0" # Pattern for N5 channels for feature extraction
  chunk_size: "768,768,768"  # Core chunk size for feature extraction
  overlap: "128,128,128"        # Overlap for feature extraction