executor: local
latency-wait: 60
rerun-triggers: mtime
use-conda: true
printshellcmds: true
cores: 1
restart-times: 0
jobs: 100
keep-going: true
# Global GPU resources (set to number of GPUs available, gpus=1 will serialize GPU jobs to avoid worker timeouts) #
resources:
  gpus: 1